In [10]:
import numpy as np
import numpy.random as rd

In [7]:
ones = np.ones(12)
print(ones)
ze = np.zeros(10)
print(ze)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
m1 = np.identity(3)
print(m1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
m2 = np.arange(5, 16)
print(m2)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [37]:
m3 = rd.rand(10)
print(m3)
m4 = rd.randn(10)
print(m4)

[0.15163215 0.55867071 0.54662027 0.83340809 0.76043066 0.44997795
 0.22409899 0.50634413 0.73643483 0.73260819]
[-0.46661914  0.01212431  0.92311597 -0.08821939  1.10330435 -1.05540364
  1.87709046 -0.65122785  0.69775756 -0.71832594]
